import type { CampaignWorldReview } from "@worldforge/shared";

export function campaignWorldReviewFixture(): CampaignWorldReview {
  return {
    campaignId: "campaign-1",
    status: "review",
    version: 2,
    contentHash: "0123456789abcdef0123456789abcdef",
    sourceDigest: "source-digest-1",
    worldSummary: "Guild trains cross a drowned coast where signal bells answer back.",
    locations: [
      {
        id: "location-a",
        name: "Lantern Gate",
        description: "The last dry terminus on the guild line.",
        kind: "macro",
        parentLocationId: null,
        tags: ["rail", "harbor"],
        isStarting: true,
      },
      {
        id: "location-b",
        name: "Bell Platform",
        description: "A signal platform suspended over the tide.",
        kind: "persistent_sublocation",
        parentLocationId: "location-a",
        tags: ["signal"],
        isStarting: false,
      },
    ],
    routes: [
      {
        id: "route-a",
        fromLocationId: "location-a",
        toLocationId: "location-b",
        travelCost: 2,
      },
    ],
    actors: [
      {
        id: "actor-a",
        kind: "person",
        controller: "agent",
        role: "key",
        name: "Mara Venn",
        summary: "A courier carrying the last valid route seal.",
        traits: ["watchful", "stubborn"],
        tags: ["courier"],
      },
      {
        id: "actor-b",
        kind: "person",
        controller: "agent",
        role: "support",
        name: "Oren Tide",
        summary: "A dispatcher who keeps the drowned rail network legible.",
        traits: ["methodical", "guarded"],
        tags: ["dispatcher"],
      },
      {
        id: "actor-c",
        kind: "person",
        controller: "agent",
        role: "support",
        name: "Sel Bell",
        summary: "A signal tender who records the bells that answer after dark.",
        traits: ["patient", "curious"],
        tags: ["signal"],
      },
      {
        id: "actor-d",
        kind: "person",
        controller: "agent",
        role: "background",
        name: "Ilya Venn",
        summary: "A former clerk who keeps copies of every revoked route seal.",
        traits: ["precise"],
        tags: ["clerk"],
      },
      {
        id: "actor-e",
        kind: "person",
        controller: "agent",
        role: "background",
        name: "Niko Salt",
        summary: "A dock medic who hears the crews' fears before departure.",
        traits: ["steady"],
        tags: ["medic"],
      },
      {
        id: "actor-f",
        kind: "person",
        controller: "agent",
        role: "key",
        name: "Rhea Quill",
        summary: "A route assessor who suspects the tide charts were changed.",
        traits: ["skeptical"],
        tags: ["assessor"],
      },
    ],
    goals: [
      {
        id: "goal-a",
        actorId: "actor-a",
        objective: "Reach Bell Platform before the tide turns.",
        motivation: "The route seal expires at dusk.",
        horizon: "immediate",
        priority: 5,
        status: "active",
      },
      {
        id: "goal-b",
        actorId: "actor-b",
        objective: "Keep the signal network legible for the night trains.",
        motivation: "Passengers will drown if the dispatch notices fail.",
        horizon: "ongoing",
        priority: 4,
        status: "active",
      },
      { id: "goal-c", actorId: "actor-c", objective: "Learn why the bell answers late.", motivation: "The next false signal could strand a train.", horizon: "immediate", priority: 4, status: "active" },
      { id: "goal-d", actorId: "actor-d", objective: "Protect the copied route seals.", motivation: "The official ledger cannot be trusted.", horizon: "ongoing", priority: 3, status: "active" },
      { id: "goal-e", actorId: "actor-e", objective: "Keep injured crews moving.", motivation: "No one should be left on the flooded line.", horizon: "immediate", priority: 3, status: "active" },
      { id: "goal-f", actorId: "actor-f", objective: "Find the altered tide chart.", motivation: "Safe crossings depend on the original marks.", horizon: "ongoing", priority: 5, status: "active" },
    ],
    relations: [
      {
        id: "relation-a",
        sourceActorId: "actor-b",
        targetActorId: "actor-a",
        relationType: "authority",
        summary: "Oren issued Mara's route seal and can revoke it.",
        intensity: 4,
      },
      { id: "relation-b", sourceActorId: "actor-a", targetActorId: "actor-c", relationType: "association", summary: "Mara relies on Sel's late bell records.", intensity: 3 },
      { id: "relation-c", sourceActorId: "actor-c", targetActorId: "actor-d", relationType: "dependency", summary: "Sel needs Ilya's copied route seals.", intensity: 2 },
      { id: "relation-d", sourceActorId: "actor-d", targetActorId: "actor-e", relationType: "association", summary: "Ilya trusts Niko with the records he cannot publish.", intensity: 3 },
      { id: "relation-e", sourceActorId: "actor-e", targetActorId: "actor-f", relationType: "alliance", summary: "Niko and Rhea keep relief crossings open.", intensity: 4 },
    ],
    placements: [
      {
        id: "placement-a",
        actorId: "actor-a",
        locationId: "location-a",
        placementKind: "present",
      },
      {
        id: "placement-b",
        actorId: "actor-b",
        locationId: "location-b",
        placementKind: "present",
      },
      { id: "placement-c", actorId: "actor-c", locationId: "location-a", placementKind: "present" },
      { id: "placement-d", actorId: "actor-d", locationId: "location-b", placementKind: "present" },
      { id: "placement-e", actorId: "actor-e", locationId: "location-a", placementKind: "present" },
      { id: "placement-f", actorId: "actor-f", locationId: "location-b", placementKind: "present" },
    ],
    pressures: [
      {
        id: "pressure-a",
        name: "Closing Route",
        description: "The tide is swallowing the last dry line.",
        trajectory: "Lantern Gate loses access to Bell Platform.",
        urgency: 5,
        actorIds: ["actor-a", "actor-b", "actor-f"],
        locationIds: ["location-a", "location-b"],
      },
    ],
    builtAt: 2000,
    acceptedAt: null,
    source: {
      premise: "A drowned rail kingdom listens for impossible bells.",
      dna: null,
      researchSummary: "Rail guilds organize the coast through signal authority.",
      sourceReferences: [{ id: "source-a", label: "Campaign premise", sourceType: "premise" }],
    },
  };
}
